# Generated by Django 3.0.7 on 2020-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200729_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
