# Generated by Django 3.0.7 on 2020-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pub_date', models.DateField(blank=True)),
                ('file', models.FileField(upload_to='journals')),
            ],
        ),
    ]
