# Generated by Django 3.0.7 on 2020-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='affiche',
            field=models.ImageField(blank=True, upload_to='affiches'),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
    ]
